# The source repo containing the sandbox-apps helm charts.
appsHelmSourceURL: https://github.com/clhain/sandbox-helm-charts.git
# The path to the sandbox-apps helm chart.
appsHelmSourcePath: charts/sandbox-apps
# The target revision of the sandbox-apps helm chart repo to pull from.
appsHelmSourceTargetRevision: HEAD

# The default sandbox-apps application branch / tag to pull from
appsSourceTargetRevision: HEAD

# clusterDomain is the domain under which all resources are deployed. e.g. example.com
clusterDomain: "localtest.me"
# clusterIngressIP is the IP address which is to be assigned to the nginx ingress controller.
clusterIngressIP:
# Disable all certificate generation and https auth callbacks (not recommended)
clusterTLSInsecure: false
# Enable a local Dex IDP with static admin account for oauth protected services.
clusterLocalAuth: true

# oidcClientID is the OIDC Client's ID to be used with oauth2 proxy.
oidcClientID: ""
# oidcClientSecret is the OIDC Client's Secret to be used with oauth2 proxy.
oidcClientSecret: ""
# oidcIssuerURL is the OIDC Issuer URL to be used with oauth2 proxy.
oidcIssuerURL: ""
# oidcPermittedEmailDomains is the set of email domains allowed to access resources behind the oauth2 proxy.
oidcPermittedEmailDomains: "*"
# Admin Pass overrides the default admin account for use with local dex authenticator
adminPass: ""
# Cookie Secret to use with Oauth2 Proxy
cookieSecret: ""

# letsEncryptContactEmail is the email address to use when registering let's encrypt certs.
letsEncryptContactEmail: ""

# Deploy auth secrets for oauthProxy
authSecretEnable: true
authSecretName: oauth-secret

# Parameter overrides to pass to the sandbox-apps helm chart.
paramOverrides:
  default.app.source.targetRevision: "{{ .Values.appsSourceTargetRevision }}"

deployArgoProject: true

# Setting to pass to the public Argo CD Helm Charts
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd:
  crds:
    # Required because argo-cd helm handles crds as templates rather than in crds directory.
    install: false
  server:
    # Set the default policy for logged in GUI users to readonly.
    rbacConfig:
      policy.default: role:readonly
    configEnabled: false
