{{- if not (index .Values "argo-cd" "server" "configEnabled") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: sandbox-base
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  oidc.config: |
    name: OIDC
    issuer: "{{ if .Values.oidcIssuerURL }}{{ .Values.oidcIssuerURL }}{{ else }}{{ if .Values.clusterTLSInsecure }}http://{{ else }}https://{{ end }}dex.{{.Values.clusterDomain}}/dex{{ end }}"
    clientID: $oauth-secret:oidc.clientId
    clientSecret: $oauth-secret:oidc.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
  resource.customizations.health.argoproj.io_Application: |-
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
  server.rbac.log.enforce.enable: "false"
  url: {{ if .Values.clusterTLSInsecure }}http{{ else }}https{{ end }}://argocd.{{ .Values.clusterDomain }}/
{{- end }}