{{ if .Values.deployArgoProject }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sandbox
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
{{- end }}