{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.authSecretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $cookieSecret := (get $secretData "cookie-secret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $clientSecret := (get $secretData "oidc.clientSecret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $clientId := (get $secretData "oidc.clientId") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $adminPass := (get $secretData "admin-password") | default (randAlphaNum 32 | b64enc | substr 0 32) }}

{{- if .Values.authSecretEnable }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authSecretName | required (printf "No authSecretName specified") }}
  labels:
    app.kubernetes.io/part-of: argocd
stringData:
  oidc.clientId: "{{ if .Values.oidcClientID }}{{ .Values.oidcClientID }}{{ else }}{{ $clientId | b64dec }}{{ end }}"
  oidc.clientSecret: "{{ if .Values.oidcClientSecret }}{{ .Values.oidcClientSecret }}{{ else }}{{ $clientSecret | b64dec }}{{ end }}"
  cookie-secret: "{{ if .Values.cookieSecret }}{{ .Values.cookieSecret }}{{ else }}{{ $cookieSecret | b64dec }}{{ end }}"
  admin-password: "{{ if .Values.adminPass }}{{ .Values.adminPass }}{{ else }}{{ $adminPass | b64dec }}{{ end }}"
{{- end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox-apps
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: sandbox
  source:
    repoURL: {{ .Values.appsHelmSourceURL }}
    path: {{ .Values.appsHelmSourcePath }}
    targetRevision: {{ .Values.appsHelmSourceTargetRevision }}
    helm:
      parameters:
        - name: clusterDomain
          value: "{{ .Values.clusterDomain }}"
        - name: clusterIngressIP
          value: "{{ .Values.clusterIngressIP }}"
        - name: clusterTLSInsecure
          value: "{{ .Values.clusterTLSInsecure }}"
        - name: clusterLocalAuth
          value: "{{ .Values.clusterLocalAuth }}"
        - name: cookieSecret
          value: "{{ if .Values.cookieSecret }}{{ .Values.cookieSecret }}{{ else }}{{ $cookieSecret | b64dec }}{{ end }}"
        - name: adminPass
          value: "{{ if .Values.adminPass }}{{ .Values.adminPass }}{{ else }}{{ $adminPass | b64dec }}{{ end }}"
        - name: oidcClientID
          value: "{{ if .Values.oidcClientID }}{{ .Values.oidcClientID }}{{ else }}{{ $clientId | b64dec }}{{ end }}"
        - name: oidcClientSecret
          value: "{{ if .Values.oidcClientSecret }}{{ .Values.oidcClientSecret }}{{ else }}{{ $clientSecret | b64dec }}{{ end }}"
        - name: oidcPermittedEmailDomains
          value: "{{ .Values.oidcPermittedEmailDomains }}"
        - name: oidcIssuerURL
          value: "{{ if .Values.oidcIssuerURL }}{{ .Values.oidcIssuerURL }}{{ else }}{{ if .Values.clusterTLSInsecure }}http://{{ else }}https://{{ end }}dex.{{.Values.clusterDomain}}/dex{{ end }}"
        - name: letsEncryptContactEmail
          value: "{{ .Values.letsEncryptContactEmail }}"
        {{- if .Values.paramOverrides }}
        {{- range $k,$v := .Values.paramOverrides }}
        - name: {{ $k }}
          value: {{ include "render-value" ( dict "value" $v "context" $) | quote}}
        {{- end }}
        {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 20s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
