{{- $secretObj := (lookup "v1" "Secret" .Values.authSecretNamespace .Values.authSecretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $clientSecret := (get $secretData "oidc.clientSecret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $clientId := (get $secretData "oidc.clientId") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $cookieSecret := (get $secretData "cookie-secret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $adminPass := (get $secretData "admin-password") | default (randAlphaNum 32 | b64enc | substr 0 32) }}

{{- if .Values.oauthProxySecretEnable }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.oauthProxyNamespace | required (printf "No oauthNamespace specified") }}
  name: {{ .Values.oauthProxyNamespace | required (printf "No oauthNamespace specified") }}

---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-proxy-creds
  namespace: {{ .Values.oauthProxyNamespace | required (printf "No oauthNamespace specified") }}
stringData:
  client-id: "{{ if .Values.oidcClientID }}{{ .Values.oidcClientID }}{{ else }}{{ $clientId | b64dec }}{{ end }}"
  client-secret: "{{ if .Values.oidcClientSecret }}{{ .Values.oidcClientSecret }}{{ else }}{{ $clientSecret | b64dec }}{{ end }}"
  cookie-secret: "{{ if .Values.cookieSecret }}{{ .Values.cookieSecret }}{{ else }}{{ $cookieSecret | b64dec }}{{ end }}"
  admin-password: "{{ if .Values.adminPass }}{{ .Values.adminPass }}{{ else }}{{ $adminPass | b64dec }}{{ end }}"
{{- end }}


{{- if .Values.clusterLocalAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-config-secret
  namespace: {{ .Values.oauthProxyNamespace | required (printf "No oauthNamespace specified") }}
stringData:
  config.yaml: |
    issuer: {{ if .Values.clusterTLSInsecure }}http{{ else }}https{{ end }}://dex.{{ .Values.clusterDomain }}/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
    connectors:
    - type: mockCallback
      id: mock
      name: Example

    oauth2:
      skipApprovalScreen: false
      alwaysShowLoginScreen: true
    staticClients:
    - id: {{ if .Values.oidcClientID }}{{ .Values.oidcClientID }}{{ else }}{{ $clientId | b64dec }}{{ end }}
      redirectURIs:
      - '{{ if .Values.clusterTLSInsecure }}http{{ else }}https{{ end }}://auth.{{ .Values.clusterDomain }}/oauth2/callback'
      - '{{ if .Values.clusterTLSInsecure }}http{{ else }}https{{ end }}://argocd.{{ .Values.clusterDomain }}/auth/callback'
      name: 'OAuth2 Proxy'
      secret: "{{ if .Values.oidcClientSecret }}{{ .Values.oidcClientSecret }}{{ else }}{{ $clientSecret | b64dec }}{{ end }}"
    enablePasswordDB: true
    staticPasswords:
    - email: "admin@example.com"
      hash: "{{ $adminPass | b64dec | bcrypt }}"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    logger:
      level: debug
{{- end }}
