{{- if .Values.oauthProxySecret.enable }}
{{- if .Values.oauthProxySecret.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.oauthProxySecret.namespace | required (printf "No oauthNamespace specified") }}
  name: {{ .Values.oauthProxySecret.namespace | required (printf "No oauthNamespace specified") }}
{{- end }}

{{- $secretObj := (lookup "v1" "Secret" .Values.oauthProxySecret.namespace .Values.oauthProxySecret.secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $cookieSecret := (get $secretData "cookie-secret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauthProxySecret.secretName | required (printf "No oauthProxySecret.secretName specified") }}
  namespace: {{ .Values.oauthProxySecret.namespace | required (printf "No oauthNamespace specified") }}
stringData:
  client-id: "{{ include "render-value" ( dict "value" .Values.oauthProxySecret.clientID  "context" $) | required (printf "No oauthProxySecret.clientID specified") }}"
  client-secret: "{{ include "render-value" ( dict "value" .Values.oauthProxySecret.clientSecret  "context" $) | required (printf "No oauthProxySecret.clientSecret specified") }}"
  cookie-secret: "{{ .Values.oauthProxySecret.cookieSecret | default ($cookieSecret | b64dec) }}"
{{- end }}
